version: '3.3'
services:
  customer-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'customer-service'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: